<?php
/**
 * Setting for client: client Id and client password
 */
define('MangoPay_ClientId', 'mosaiclab');
define('MangoPay_ClientPassword', 'FPpPoofN837Y0MxRXnKVH31kJ2dLc54oT481R55KEkjeQ6Bph4');

/**
 * Base URL to MangoPay API
 */
//define('MangoPay_BaseUrl', 'https://mangopay-api-inte.leetchi.com');

/**
 * Constant to switch debug mode - display all request and response data
 */
define('MangoPay_DebugMode', 0);
//define('MangoPay_DebugMode', 1);
