<?php
namespace MangoPay;

/**
 * Configuration settings
 */
class Configuration {
	
    /**
     * Client Id
     * @var string 
     */
    public $ClientId;
	
    /**
     * Client password
     * @var string 
     */
    public $ClientPassword;
	
    /**
     * Base URL to MangoPay API
     * @var string 
     */
    public $BaseUrl;
    
//    /**
//     * Authentication type
//     * @var string
//     */
//    public $AuthenticationType = "Strong";

}