sudo: false

dist: xenial

language: php

php:
#  - 5.6
#  - 7.0
#  - 7.1
#  - 7.2
#  - 7.3
#  - 7.4
  - 8.0

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction -o --ignore-platform-reqs

script: ./vendor/bin/phpunit
