<?php

namespace MangoPay;

/**
 * Business sector
 */
class Sector
{
    public const RENTALS = "RENTALS";

    public const STORES_FASHION_ACCESSORIES_OBJECTS = "STORES_FASHION_ACCESSORIES_OBJECTS";

    public const BEAUTY_COSMETICS_HEALTH = "BEAUTY_COSMETICS_HEALTH";

    public const FOOD_WINE_RESTAURANTS = "FOOD_WINE_RESTAURANTS";

    public const HOSPITALITY_TRAVEL_CORIDING = "HOSPITALITY_TRAVEL_CORIDING";

    public const ART_MUSIC_ENTERTAINMENT = "ART_MUSIC_ENTERTAINMENT";

    public const FURNITURE_GARDEN = "FURNITURE_GARDEN";

    public const SERVICES_JOBBING_EDUCATION = "SERVICES_JOBBING_EDUCATION";

    public const SPORT_RECREATION_ACTIVITIES = "SPORT_RECREATION_ACTIVITIES";

    public const TICKETING = "TICKETING";
}
