<?php

namespace MangoPay;

/**
 * Business sector
 */
class Sector
{
    const RENTALS = "RENTALS";

    const STORES_FASHION_ACCESSORIES_OBJECTS = "STORES_FASHION_ACCESSORIES_OBJECTS";

    const BEAUTY_COSMETICS_HEALTH = "BEAUTY_COSMETICS_HEALTH";

    const FOOD_WINE_RESTAURANTS = "FOOD_WINE_RESTAURANTS";

    const HOSPITALITY_TRAVEL_CORIDING = "HOSPITALITY_TRAVEL_CORIDING";

    const ART_MUSIC_ENTERTAINMENT = "ART_MUSIC_ENTERTAINMENT";

    const FURNITURE_GARDEN = "FURNITURE_GARDEN";

    const SERVICES_JOBBING_EDUCATION = "SERVICES_JOBBING_EDUCATION";

    const SPORT_RECREATION_ACTIVITIES = "SPORT_RECREATION_ACTIVITIES";

    const TICKETING = "TICKETING";
}
