<?php
namespace MangoPay;

/**
 * Request type enum
 */
class RequestType {
    const GET = 'GET';
    const POST = 'POST';
    const PUT = 'PUT';
    const DELETE = 'DELETE';
}

/**
 * Person type for users
 */
class PersonType {
    const Natural = 'NATURAL';
    const Legal = 'LEGAL';
}

///**
// * Class (enum) with authentication type
// */
//class AuthenticationType {
//    const Basic = 'Basic';
//    const Strong = 'Strong';
//}
