<?php

namespace MangoPay;

/**
 * Class represents file object
 */
class File {
    
    /**
     * 
     * @var String
     * @access public
     */
    public $File;
    
    /**
     * URL for file
     * @var String
     * @access public
     */
    public $FileUrl;
    
    /**
     * Type of file. Possible: 'JPEG', 'GIF', 'PDF'
     * @var String
     * @access public
     */
    public $FileType;
    
}
